Fixed issue with CI release notes not finding version number.

diff --git a/.github/workflows/release-notes.yml b/.github/workflows/release-notes.yml
--- a/.github/workflows/release-notes.yml
+++ b/.github/workflows/release-notes.yml
@@ -25,17 +25,16 @@ jobs:
         uses: ./.github/actions/calculate-version
 
       - name: Install GitReleaseManager
-        uses: gittools/actions/gitreleasemanager/setup@v0.9.11
+        uses: gittools/actions/gitreleasemanager/setup@v0.9.13
         with:
           versionSpec: '0.13.0'
 
-      - name: Create Release
-        uses: gittools/actions/gitreleasemanager/create@v0.9.11
-        with:
-          token: ${{ secrets.GITHUB_TOKEN }}
-          owner: 'corgibytes'
-          repository: 'ruby-debug-ide'
-          milestone: 'v${{ steps.gitversion.outputs.majorMinorPatch }}'
+      # If there are no closed issues generating the Github Release will fail because it raises an exception.
+      # Work around this by checking for success or no closed issue errors.
+      - name: Create Release ${{ env.MajorMinorPatch }}
+        run: |
+          dotnet gitreleasemanager create --owner trust-consulting-group --repository trust_v1 --token ${{ secrets.GITHUB_TOKEN }} --milestone v${{ env.GitVersion_MajorMinorPatch }} --logFilePath output.txt || true
+          cat output.txt | grep 'No closed issues have been found for milestone\|Drafted release is available at'
 
       - name: 'Generate Change Log'
         run: |
